"""empty message

Revision ID: e0bad4c8608d
Revises: 8420fd27ce06
Create Date: 2020-09-19 08:35:26.994443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0bad4c8608d'
down_revision = '8420fd27ce06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('movies', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.alter_column('actors', 'movie_id', existing_type=sa.Integer(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'image_link')
    op.drop_column('actors', 'image_link')
    op.alter_column('actors', 'movie_id', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###
